name: macOS/Ubuntu build and test cpp-module-03

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  ubuntu_build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ex00 build
      run:  make -C module-03/ex00
    - name: ex00 test
      run:  make test -C module-03/ex00
    - name: ex01 build
      run:  make -C module-03/ex01
    - name: ex01 test
      run:  make test -C module-03/ex01
    - name: ex02 build
      run:  make -C module-03/ex02
    - name: ex02 test
      run:  make test -C module-03/ex02
    - name: ex03 build
      run:  make -C module-03/ex03
    - name: ex03 test
      run:  make test -C module-03/ex03

  macos_build_and_test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: ex00
      run:  make -C module-03/ex00
    - name: ex00 test
      run:  make test -C module-03/ex00
    - name: ex01 build
      run:  make -C module-03/ex01
    - name: ex01 test
      run:  make test -C module-03/ex01
    - name: ex02 build
      run:  make -C module-03/ex02
    - name: ex02 test
      run:  make test -C module-03/ex02
    - name: ex03 build
      run:  make -C module-03/ex03
    - name: ex03 test
      run:  make test -C module-03/ex03
