name: macOS/Ubuntu CI cpp-module-03

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  ubuntu_build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ex00 build
      run:  make -C module-03/ex00
    - name: ex00 test
      run:  make test -C module-03/ex00

  macos_build_and_test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: ex00
      run:  make -C module-03/ex00
    - name: ex00 test
      run:  make test -C module-03/ex00
