name: macOS/Ubuntu CI cpp-module-02

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu_compile_check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ex00
      run:  make -C module-02/ex00
    - name: ex01
      run:  make -C module-02/ex01
    - name: ex02
      run:  make -C module-02/ex02

  macos_compile_check:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: ex00
      run:  make -C module-02/ex00
    - name: ex01
      run:  make -C module-02/ex01
    - name: ex02
      run:  make -C module-02/ex02
