name: macOS/Ubuntu build cpp-module-09

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

env:
  EX00_DIR: module-09/ex00

jobs:
  macos_build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: ex00 build
      run:  make -C $EX00_DIR && make fclean -C $EX00_DIR
