name: macOS/Ubuntu build and test cpp-module-00

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

env:
  EX00_DIR: module-00/ex00
  EX00_EXE: module-00/ex00/megaphone
  EX01_DIR: module-00/ex01
  EX01_EXE: module-00/ex01/phonebook
  EX02_DIR: module-00/ex02
  EX02_EXE: module-00/ex02/account

jobs:
  ubuntu_build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ex00 build
      run:  make -C $EX00_DIR && make fclean -C $EX00_DIR
    - name: ex00 test
      run:  make test -C $EX00_DIR && make fclean -C $EX00_DIR
    - name: ex01 build
      run:  make -C $EX01_DIR && make fclean -C $EX01_DIR
    - name: ex01 test
      run:  make test -C $EX01_DIR && make fclean -C $EX01_DIR
    - name: ex02 build
      run:  make -C $EX02_DIR && make fclean -C $EX02_DIR
    - name: ex02 test
      run:  make test -C $EX02_DIR && make fclean -C $EX02_DIR

  macos_build_and_test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: ex00 build
      run:  make -C $EX00_DIR && make fclean -C $EX00_DIR
    - name: ex00 test
      run:  make test -C $EX00_DIR && make fclean -C $EX00_DIR
    - name: ex01 build
      run:  make -C $EX01_DIR && make fclean -C $EX01_DIR
    - name: ex01 test
      run:  make test -C $EX01_DIR && make fclean -C $EX01_DIR
    - name: ex02 build
      run:  make -C $EX02_DIR && make fclean -C $EX02_DIR
    - name: ex02 test
      run:  make test -C $EX02_DIR && make fclean -C $EX02_DIR