name: macOS/Ubuntu build and test cpp-module-04

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

env:
  EX00_DIR: module-04/ex00
  EX00_EXE: module-04/ex00/Polymorphism
  EX01_DIR: module-04/ex01
  EX01_EXE: module-04/ex01/i_dont_want_to_set_the_world_on_fire

jobs:
  ubuntu_build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ex00 build
      run:  make -C $EX00_DIR && make fclean -C $EX00_DIR
    - name: ex00 test
      run:  make test -C $EX00_DIR && make fclean -C $EX00_DIR
    - name: ex00 unit_test
      run:  make TESTS=1 -C $EX00_DIR && ./$EX00_EXE && make fclean -C $EX00_DIR
    - name: ex01 build
      run:  make -C $EX01_DIR && make fclean -C $EX01_DIR
    - name: ex01 test
      run:  make test -C $EX01_DIR && make fclean -C $EX01_DIR
    - name: ex01 unit_test
      run:  make TESTS=1 -C $EX01_DIR && ./$EX01_EXE && make fclean -C $EX01_DIR

  macos_build_and_test:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: ex00 build
      run:  make -C $EX00_DIR && make fclean -C $EX00_DIR
    - name: ex00 test
      run:  make test -C $EX00_DIR && make fclean -C $EX00_DIR
    - name: ex00 unit_test
      run:  make TESTS=1 -C $EX00_DIR && ./$EX00_EXE && make fclean -C $EX00_DIR
    - name: ex01 build
      run:  make -C $EX01_DIR && make fclean -C $EX01_DIR
    - name: ex01 test
      run:  make test -C $EX01_DIR && make fclean -C $EX01_DIR
    - name: ex01 unit_test
      run:  make TESTS=1 -C $EX01_DIR && ./$EX01_EXE && make fclean -C $EX01_DIR