name: macOS/Ubuntu CI cpp-module-01

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu_compile_check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ex00
      run:  make -C module-01/ex00
    - name: ex01
      run:  make -C module-01/ex01
    - name: ex02
      run:  make -C module-01/ex02
    - name: ex03
      run:  make -C module-01/ex03
    - name: ex04
      run:  make -C module-01/ex04
    - name: ex05
      run:  make -C module-01/ex05
  
  macos_compile_check:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: ex00
      run:  make -C module-01/ex00
    - name: ex01
      run:  make -C module-01/ex01
    - name: ex02
      run:  make -C module-01/ex02
    - name: ex03
      run:  make -C module-01/ex03
    - name: ex04
      run:  make -C module-01/ex04
    - name: ex05
      run:  make -C module-01/ex05
