name: macOS/Ubuntu build cpp-module-06

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

env:
  EX00_DIR: module-06/ex00
  EX01_DIR: module-06/ex01
  EX02_DIR: module-06/ex02

jobs:
  macos_build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: ex00 build
      run:  make -C $EX00_DIR && make fclean -C $EX00_DIR
    - name: ex01 build
      run:  make -C $EX01_DIR && make fclean -C $EX01_DIR
    - name: ex02 build
      run:  make -C $EX02_DIR && make fclean -C $EX02_DIR
      
  ubuntu_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ex00 build
      run:  make -C $EX00_DIR && make fclean -C $EX00_DIR
    - name: ex01 build
      run:  make -C $EX01_DIR && make fclean -C $EX01_DIR
    - name: ex02 build
      run:  make -C $EX02_DIR && make fclean -C $EX02_DIR
